name: Deploy To Dev Env

env:
  APP_NAME: tms-service-gateway

on:
  workflow_dispatch
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean verify

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
            
      - name: Build and upload dev docker image to GHCR
        run: |
           docker build . --tag ghcr.io/${{ github.actor }}/dev-${{ env.APP_NAME }}:latest
           docker push ghcr.io/${{ github.actor }}/dev-${{ env.APP_NAME }}:latest
